version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    env_file:
      - .env
    volumes:
      - ./:/bot
      - /app/node_modules
  mongo:
    image: mongo:latest
    ports:
      - 0:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
